### ISSUE TITLE
[FEATURE] Implementing Collaborative Work - Sharing

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/CmyPlot#1]
The first and foremost addition to the existing project would be adding collaborators who can view the graphs and tables in real-time and can view the dataset as per their convenience. This will majorly help the people who are working in a group so that they can convey their messages and thoughts in real-time.

**Comment by thosaniparth** [comment]
I have an idea that we should add the share button which will share the graphs in real-time via email.

**Comment by nsshah14** [comment]
I am not able to get the updated graph from the page and send it to python's sendmail function.

**Comment by BosamiyaSimran** [comment]
I tried storing the graph in session storage which can be further used for sharing. Still working on it.

**Comment by BosamiyaSimran** [comment]
Session Storage didn't work out. Trying to save image locally and send it as an email

**Comment by thosaniparth** [comment]
What's the update on storing the image? Are we able to extract it from the system and send it over the mail?

**Comment by BosamiyaSimran** [comment]
Successfully storing and sharing the image via email
