### ISSUE TITLE
[BUG] Asset file deletion

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/CmyPlot#10]
Please delete the assets file after sending emails via the share button on the graphs page.

**Comment by BosamiyaSimran** [comment]
Resolved.

**Comment by nsshah14** [comment]
I am getting the error **No file named asset.pkl**. So instead of deleting the file, I think we should truncate that file.

**Comment by BosamiyaSimran** [comment]
Resolved. Truncating or deleting not needed as it overwrites the asset file every time the callback gets executed.

**Comment by nsshah14** [comment]
Ok. It is working now. Thank you
