### ISSUE TITLE
[FEATURE] Application Deployment on the web

### ISSUE THREAD

**Issue by nsshah14** [thosaniparth/CmyPlot#11]
Instead of creating a standalone application, hosting it on the web would attract larger community and will help users to get access to their graphs anywhere on the world.  So we should host this project on Heroku which is a free hosting service.

**Comment by thosaniparth** [comment]
There were issues while deployment on Heroku and the path of files were not found while adding them online. Is it still pending or do we have an update for the deployment?

**Comment by nsshah14** [comment]
Instead of actually installing the application, we should give the absolute path of the files for import. Standalone application is not getting installed on Heroku and has problems with file paths.

**Comment by nsshah14** [comment]
Application was deployed after giving absolute paths. It is now hosted at [this link](https://cmyplot-seproject.herokuapp.com/).
