### ISSUE TITLE
Code Formatters - Black on Python

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/CmyPlot#17]
We should use a feature that will check the syntax and formatting and also correct them for better visibility of the codebase. We can use Black for Python.

**Comment by nsshah14** [comment]
Black is only checking for formatting and not editing the files. The workflow file needs to be revised to check the command.

**Comment by nsshah14** [comment]
I updated the GitHub workflows file with the updated command which edits all the files and does code formatting. Closing this issue now.
