### ISSUE TITLE
[FEATURE] Allow support for more Graphs in the application

### ISSUE THREAD

**Issue by nsshah14** [thosaniparth/CmyPlot#2]
The project is just having a single graph type. It is very limited depiction of what the data actually is. We should add other graph types like pie chart and scatter plots to gain more understanding of data.

**Comment by BosamiyaSimran** [comment]
I have added two additional graphs - Line chart and Bar chart

**Comment by nsshah14** [comment]
We can add these graphs for the time being but we need to update the page on callbacks as various graphs have different options.

**Comment by BosamiyaSimran** [comment]
Added additional graphs for now.
