### ISSUE TITLE
[FEATURE] Informative Graphs

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/CmyPlot#4]
Data Visualization is done to visualize data into a simpler and understandable form. One of the important factors can understand " What is the nature of data ? ".
Along with the plots of the graph additional information of the data like Mean, Median, Mode Standard Deviation, etc would be helpful for the user to understand the nature of the data.

**Comment by thosaniparth** [comment]
I have added the mean, median, and mode of the Labels of the graph and it will also show column attributes that are integer or float. It will throw error on string data types.

**Comment by ParthJinturkar** [comment]
Updated the mean, median, mode values with standard deviation for both the X and Y labels.
