### ISSUE TITLE
[FEATURE] Add other details in hover of the graph

### ISSUE THREAD

**Issue by BosamiyaSimran** [thosaniparth/CmyPlot#6]
There are parameters for adding Hover text to the points on the graph. it would be awesome if the user could specific what to hover while including variables.

**Comment by thosaniparth** [comment]
That's a good idea We can include the column values of the dataset to the hover of the graph points so that the user can select the column attribute and can hover over the points and can view other details apart from X and Y labels.

**Comment by thosaniparth** [comment]
I have added the details to the hover of the data points which will be shown to the user on the selection of attributes from the dropdown in filters.

**Comment by BosamiyaSimran** [comment]
The feature seems appropriate and an additional thing for future scope could be that we can include multiple other features on the hover so the user can view the information on the hover button later on. Also, selecting hover attribute shouldn't be mandatory.
