### ISSUE TITLE
Enhancement of Table tab with Dynamic Rows 

### ISSUE THREAD

**Issue by nsshah14** [thosaniparth/CmyPlot#7]
Currently, the table just gives us a feature to filter the data but we can extend this concept and give dynamic view of the table by providing the user to choose on how many rows does he wants to see on the page. We can also give a page count upto which the user wants to see the data on the table

**Comment by thosaniparth** [comment]
I have added the page count value that will limit the data to that number of rows. So that the user is not overwhelmed with all data at once and can even check the data according to his wish by putting the value of a number of rows on a particular page.

**Comment by nsshah14** [comment]
This is a good feature as the user don't want to see the whole data all at once but only want a certain data to be seen.
